services:
  mysql:
    image: mysql:8.0
    env_file:
      - ./.env
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: $PASSWORD
      MYSQL_DATABASE: $DATABASE
    ports:
      - "$DB_PORT:$DB_PORT"
    volumes:
      - mysql_data:/var/lib/mysql
  app: 
    build: .
    depends_on:
      - mysql
    links:
      - mysql
    ports:
      - "$PORT:$PORT"
      
volumes:
  mysql_data: