services:
  mysql:
    image: mysql:8.0
    env_file:
      - ./.env
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: $PASSWORD
      MYSQL_DATABASE: $DATABASE
    ports:
      - "$DB_PORT:$DB_PORT"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 1m30s
      timeout: 5s
      retries: 5
      start_period: 10s

  app: 
    build: .
    depends_on:
      mysql:
        condition: service_healthy
    links:
      - mysql
    ports:
      - "$PORT:$PORT"
      
volumes:
  mysql_data: