name: CI/CD - Build & Deploy Express API with MySQL

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: ⏬ Clonar repositorio
      uses: actions/checkout@v3
      
    - name: 🔐 Iniciar sesión en Tailscale
      uses: tailscale/github-action@v2
      with:
        authkey: ${{ secrets.TAILSCALE_AUTH_KEY }}    

    - name: 📦 Enviar archivos al servidor por SSH
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        source: "."
        target: "~/mi-api-express"

    - name: 🚀 Ejecutar docker-compose en el servidor
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        script: |
          mkdir -p ~/mi-api-express
          cd ~/mi-api-express
          docker-compose down
          docker-compose build --no-cache
          docker-compose up -d
